funeral_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main.views import bad_url

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('<str:name>', bad_url),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.welcome_view, name='welcome'),
    path('service', views.service_view, name='service'),
    path('about', views.about_view, name='about'),
    path('contact', views.contact_view, name='contact'),
    path('success', views.success_view, name='success'),
    path('<str:name>', views.bad_url)
]

main/models.py
from django.db import models


class Message(models.Model):
    name = models.CharField(max_length=200, verbose_name="Ваше имя")
    number = models.CharField(max_length=50, verbose_name="Номер телефона")
    email = models.EmailField(verbose_name="Почта")
    message = models.TextField(verbose_name="Сообщение")

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=300, verbose_name='сервис')
    content = models.TextField(verbose_name='content')
    image = models.ImageField(upload_to='./image/')

    def __str__(self):
        return self.name


class Client(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя')
    image = models.ImageField(upload_to='./user/', default='./image/avatar.png')
    content = models.TextField(verbose_name='содержание')

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

main/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .models import Message, Service, Client
from .forms import MessageForm
from .function import post_success


def welcome_view(request):
    services = Service.objects.all()
    clients = Client.objects.all()
    if request.method == 'POST':
        return post_success(request)
    return render(request, 'main/welcome.html', {'services': services, 'clients': clients})


def service_view(request):
    services = Service.objects.all()

    return render(request, 'main/service.html', {'services': services})


def about_view(request):
    return render(request, 'main/about.html')


def contact_view(request):
    if request.method == 'POST':
        return post_success(request)
    return render(request, 'main/contact.html')


def success_view(request):
    return render(request, 'main/success.html')


def bad_url(request, name):
    return redirect('main:welcome')
    # services = Service.objects.all()
    # clients = Client.objects.all()
    # if request.method == 'POST':
    #     return post_success(request)
    # return render(request, 'main/welcome.html', {'services': services, 'clients': clients})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <!-- Basic -->
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <!-- Site Metas -->
    <meta name="keywords" content="РИТУАЛЬНЫЕ УСЛУГИ В УЗБЕКИСТАНЕ РАБОТАЕМ КРУГЛОСУТОЧНО"/>
    <meta name="description" content=""/>
    <meta name="author" content="github.com/TalantDeveloper"/>
    <link rel="shortcut icon" href="{% static 'images/favoricon.svg' %}" type='icon'>

    <title> Ритуальные услуги в Узбекистане </title>
    <meta name="og:url" content="https://www.ritualniuslugi.uz">
    <meta name="og:title" content="РИТУАЛЬНЫЕ УСЛУГИ В Узбекистане">
    <meta name="og:description"
          content="РИТУАЛЬНЫЕ УСЛУГИ В УЗБЕКИСТАНЕ РАБОТАЕМ КРУГЛОСУТОЧНО Ритуальное агентство работает для того, чтобы освободить Вас от траурных хлопот, которые весьма тяжко переносить в дни, последовавшие после смерти близких людей. Наше ритуальное бюро берёт на себя все организационные моменты, связанные с погребением, чтобы родственники могли проводить умершего в последний путь, не отвлекаясь на мирские заботы.">
    <meta name="og:image" content="{% static 'images/favoricon.svg' %}">
    <meta name="title" content="РИТУАЛЬНЫЕ УСЛУГИ В Узбекистане">
    <meta name="description"
          content="РИТУАЛЬНЫЕ УСЛУГИ В УЗБЕКИСТАНЕ РАБОТАЕМ КРУГЛОСУТОЧНО Ритуальное агентство работает для того, чтобы освободить Вас от траурных хлопот, которые весьма тяжко переносить в дни, последовавшие после смерти близких людей. Наше ритуальное бюро берёт на себя все организационные моменты, связанные с погребением, чтобы родственники могли проводить умершего в последний путь, не отвлекаясь на мирские заботы.">

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">


    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"/>

    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet"/>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    <!-- responsive style -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet"/>

</head>

<body>

{% block content %}

{% endblock %}

<!-- info section -->

<section class="info_section layout_padding2">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-3 info_col">
                <div class="info_contact">
                    <h4>
                        Адрес
                    </h4>
                    <div class="contact_link_box">
                        <a target="_blank"
                           href="https://www.google.com/maps/place/Toshkent+davlat+stomatologiya+instituti+eski/@41.3082914,69.2994367,17z/data=!4m6!3m5!1s0x38aef527cfd7beab:0x41490626bc752d26!8m2!3d41.309198!4d69.2990049!16s%2Fg%2F11bzs4xs68?entry=ttu">
                            <i class="fa fa-map-marker" aria-hidden="true"></i>
                            <span>
                                Расположение
                            </span>
                        </a>
                        <a href="tel:+998903529097" target="_blank">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            <span>
                                : +998903529097
                            </span>
                        </a>
                        <a href="https://t.me/Ritualniyuslugi" target="_blank">
                            <i class="fa fa-telegram" aria-hidden="true"></i>
                            <span>
                  Ritualniyuslugi
                </span>
                        </a>
                    </div>
                </div>
                <div class="info_social">
                    <a href="https://www.whatsapp.com/+998903529097">
                        <i class="fa fa-whatsapp" aria-hidden="true"></i>
                    </a>
                    <a href="https://t.me/+998903529097">
                        <i class="fa fa-telegram" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 info_col">
                <div class="info_detail">
                    <h4>
                        Информация
                    </h4>
                    <p>
                        ул. Тараккиет, 103, г. Ташкент, Узбекистан
                    </p>
                </div>
            </div>
            <div class="col-md-6 col-lg-2 mx-auto info_col">
                <div class="info_link_box">
                    <h4>
                        Ссылки
                    </h4>
                    <div class="info_links">
                        <a class="active" href="{% url 'main:welcome' %}">
                            Главная
                        </a>
                        <a class="" href="{% url 'main:service' %}">
                            Услуги
                        </a>
                        <a class="" href="{% url 'main:about' %}">
                            О нас
                        </a>
                        <a class="" href="{% url 'main:contact' %}">
                            Связаться с нами
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 info_col ">
                <h4>
                    Подписаться
                </h4>
                <form action="" method="get">
                    {% csrf_token %}
                    <input type="email" placeholder="Введите почту"/>
                    <button type="submit">
                        Подписаться
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>

<!-- end info section -->

<!-- footer section -->
<section class="footer_section">
    <div class="container">
        <p>
            &copy; <span id="displayYear"></span>. Все права защищены.
            <a href="https://github.com/TalantDeveloper" target="_blank">TalantDeveloper</a>
        </p>
    </div>
</section>
<!-- footer section -->

<!-- jQery -->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- popper js -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<!-- bootstrap js -->
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<!-- owl slider -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
</script>
<!-- custom js -->
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
<!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
</script>
<!-- End Google Map -->

</body>

</html>

templates/base_sub.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <!-- Basic -->
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <!-- Site Metas -->
    <meta name="keywords" content="РИТУАЛЬНЫЕ УСЛУГИ В УЗБЕКИСТАНЕ РАБОТАЕМ КРУГЛОСУТОЧНО"/>
    <meta name="description" content=""/>
    <meta name="author" content="github.com/TalantDeveloper"/>
    <link rel="shortcut icon" href="{% static 'images/favoricon.svg' %}" type='icon'>

    <title> Ритуальные услуги в Узбекистане </title>
    <meta name="og:url" content="https://www.ritualniuslugi.uz">
    <meta name="og:title" content="РИТУАЛЬНЫЕ УСЛУГИ В Узбекистане">
    <meta name="og:description"
          content="РИТУАЛЬНЫЕ УСЛУГИ В УЗБЕКИСТАНЕ РАБОТАЕМ КРУГЛОСУТОЧНО Ритуальное агентство работает для того, чтобы освободить Вас от траурных хлопот, которые весьма тяжко переносить в дни, последовавшие после смерти близких людей. Наше ритуальное бюро берёт на себя все организационные моменты, связанные с погребением, чтобы родственники могли проводить умершего в последний путь, не отвлекаясь на мирские заботы.">
    <meta name="og:image" content="{% static 'images/favoricon.svg' %}">
    <meta name="title" content="РИТУАЛЬНЫЕ УСЛУГИ В Узбекистане">
    <meta name="description"
          content="РИТУАЛЬНЫЕ УСЛУГИ В УЗБЕКИСТАНЕ РАБОТАЕМ КРУГЛОСУТОЧНО Ритуальное агентство работает для того, чтобы освободить Вас от траурных хлопот, которые весьма тяжко переносить в дни, последовавшие после смерти близких людей. Наше ритуальное бюро берёт на себя все организационные моменты, связанные с погребением, чтобы родственники могли проводить умершего в последний путь, не отвлекаясь на мирские заботы.">

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">


    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"/>

    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet"/>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    <!-- responsive style -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet"/>

</head>

<body class="sub_page">

{% block content %}

{% endblock %}

<!-- info section -->

<section class="info_section layout_padding2">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-3 info_col">
                <div class="info_contact">
                    <h4>
                        Адрес
                    </h4>
                    <div class="contact_link_box">
                        <a target="_blank"
                           href="https://www.google.com/maps/place/Toshkent+davlat+stomatologiya+instituti+eski/@41.3082914,69.2994367,17z/data=!4m6!3m5!1s0x38aef527cfd7beab:0x41490626bc752d26!8m2!3d41.309198!4d69.2990049!16s%2Fg%2F11bzs4xs68?entry=ttu">
                            <i class="fa fa-map-marker" aria-hidden="true"></i>
                            <span>
                                Расположение
                            </span>
                        </a>
                        <a href="tel:+998903529097" target="_blank">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            <span>
                                : +998903529097
                            </span>
                        </a>
                        <a href="https://t.me/Ritualniyuslugi" target="_blank">
                            <i class="fa fa-telegram" aria-hidden="true"></i>
                            <span>
                  Ritualniyuslugi
                </span>
                        </a>
                    </div>
                </div>
                <div class="info_social">

                    <a href="https://www.whatsapp.com/+998903529097">
                        <i class="fa fa-whatsapp" aria-hidden="true"></i>
                    </a>
                    <a href="https://t.me/+998903529097">
                        <i class="fa fa-telegram" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 info_col">
                <div class="info_detail">
                    <h4>
                        Информация
                    </h4>
                    <p>
                        ул. Тараккиет, 103, г. Ташкент, Узбекистан
                    </p>
                </div>
            </div>
            <div class="col-md-6 col-lg-2 mx-auto info_col">
                <div class="info_link_box">
                    <h4>
                        Ссылки
                    </h4>
                    <div class="info_links">
                        <a class="active" href="{% url 'main:welcome' %}">
                            Главная
                        </a>
                        <a class="" href="{% url 'main:service' %}">
                            Услуги
                        </a>
                        <a class="" href="{% url 'main:about' %}">
                            О нас
                        </a>
                        <a class="" href="{% url 'main:contact' %}">
                            Связаться с нами
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 info_col ">
                <h4>
                    Подписаться
                </h4>
                <form action="" method="get">
                    {% csrf_token %}
                    <input type="email" placeholder="Введите почту"/>
                    <button type="submit">
                        Подписаться
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>

<!-- end info section -->

<!-- footer section -->
<section class="footer_section">
    <div class="container">
        <p>
            &copy; <span id="displayYear"></span>. Все права защищены.
            <a href="https://github.com/TalantDeveloper" target="_blank">TalantDeveloper</a>
        </p>
    </div>
</section>
<!-- footer section -->

<!-- jQery -->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- popper js -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>

<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
</script>
<!-- custom js -->
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
<!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
</script>
<!-- End Google Map -->

</body>

</html>

templates/main/about.html
{% extends 'base_sub.html' %}
{% load static %}
{% block content %}

    <!-- slider section -->
    <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section">
            <div class="header_top">
                <div class="container-fluid ">
                    <div class="contact_nav">
                        <a href="tel:+998903529097">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            <span>
                            Вызов : +998903529097
                            </span>
                        </a>
                        <a href="mailto:demo@gmail.com">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                            <span>
                            Почта : demo@gmail.com
                            </span>
                        </a>
                        <a href="https://www.google.com/maps/place/Toshkent+davlat+stomatologiya+instituti+eski/@41.3087803,69.299029,19.01z/data=!4m6!3m5!1s0x38aef527cfd7beab:0x41490626bc752d26!8m2!3d41.309198!4d69.2990049!16s%2Fg%2F11bzs4xs68?entry=ttu"
                           target="_blank">
                            <i class="fa fa-map-marker" aria-hidden="true"></i>
                            <span>
                                Расположение
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="header_bottom">
                <div class="container-fluid">
                    <nav class="navbar navbar-expand-lg custom_nav-container ">
                        <a class="navbar-brand" href="{% url 'main:welcome' %}">
                            <span>
                                Ритуальные услуги
                                <img src="{% static 'images/favoricon.svg' %}" alt="" width="50">
                            </span>
                        </a>

                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class=""> </span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav  ">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:welcome' %}">
                                        Главная
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:service' %}">
                                        Услуги
                                    </a>
                                </li>
                                <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'main:about' %}">
                                        О нас
                                        <span class="sr-only">(current)</span>

                                    </a>

                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:contact' %}">
                                        Связаться с нами
                                    </a>
                                </li>

                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </header>
        <!-- end header section -->
    </div>
    <!-- end slider section -->

    <!-- about section -->
    <section class="about_section layout_padding">
        <div class="container  ">
            <div class="row">
                <div class="col-md-6">
                    <div class="detail-box">
                        <div class="heading_container">
                            <h2>
                                О <span>нас</span>
                            </h2>
                        </div>
                        <p>
                            Ритуальное агентство работает для того, чтобы освободить Вас от траурных хлопот, которые
                            весьма тяжко переносить в дни, последовавшие после смерти близких людей.
                            Наше ритуальное бюро берёт на себя все организационные моменты, связанные с погребением,
                            чтобы родственники могли проводить умершего в последний путь, не отвлекаясь на мирские
                            заботы.
                        </p>

                    </div>
                </div>
                <div class="col-md-6 ">
                    <div class="img-box">
                        <img src="{% static 'images/about.png' %}" alt="">
                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- end about section -->

{% endblock %}

templates/main/contact.html
{% extends 'base_sub.html' %}
{% load static %}
{% block content %}

    <!-- slider section -->
    <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section">
            <div class="header_top">
                <div class="container-fluid ">
                    <div class="contact_nav">
                        <a href="tel:+998903529097">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            <span>
                            Вызов : +998903529097
                            </span>
                        </a>
                        <a href="mailto:demo@gmail.com">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                            <span>
                            Почта : demo@gmail.com
                            </span>
                        </a>
                        <a href="https://www.google.com/maps/place/Toshkent+davlat+stomatologiya+instituti+eski/@41.3087803,69.299029,19.01z/data=!4m6!3m5!1s0x38aef527cfd7beab:0x41490626bc752d26!8m2!3d41.309198!4d69.2990049!16s%2Fg%2F11bzs4xs68?entry=ttu"
                           target="_blank">
                            <i class="fa fa-map-marker" aria-hidden="true"></i>
                            <span>
                                Расположение
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="header_bottom">
                <div class="container-fluid">
                    <nav class="navbar navbar-expand-lg custom_nav-container ">
                        <a class="navbar-brand" href="{% url 'main:welcome' %}">
                            <span>
                                Ритуальные услуги
                                <img src="{% static 'images/favoricon.svg' %}" alt="" width="50">
                            </span>
                        </a>

                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class=""> </span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav  ">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:welcome' %}">
                                        Главная
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:service' %}">
                                        Услуги
                                    </a>
                                </li>
                                <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'main:about' %}">
                                        О нас
                                        <span class="sr-only">(current)</span>

                                    </a>

                                </li>
                                <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'main:contact' %}">
                                        Связаться с нами
                                        <span class="sr-only">(current)</span>
                                    </a>
                                </li>

                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </header>
        <!-- end header section -->
    </div>
    <!-- end slider section -->

    <!-- contact section -->
    <section class="contact_section">
        <br><br>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-md-5 offset-md-1">
                    <div class="heading_container">
                        <h2>
                            СВЯЗАТЬСЯ С НАМИ
                        </h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-5 offset-md-1">
                    <div class="form_container contact-form">
                        <form action="" method="POST">
                            {% csrf_token %}
                            <div>
                                <input name="name" type="text" placeholder="Ваше имя"/>
                            </div>
                            <div>
                                <input name="number" type="text" placeholder="Номер телефона"/>
                            </div>
                            <div>
                                <input name="email" type="email" placeholder="Почта"/>
                            </div>
                            <div>
                                <input name="message" type="text" class="message-box" placeholder="Сообщение"/>
                            </div>
                            <div class="btn_box">
                                <button>
                                    ОТПРАВЛЯТЬ
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-7 col-md-6 px-0">
                    <div class="map_container">
                        <div class="mapouter">
                            <div class="gmap_canvas">
                                <iframe src="https://maps.google.com/maps?q=%D0%A2%D0%B0%D1%88%D0%BA%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B8%D0%B9%20%D0%A1%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9%20%D0%98%D0%BD%D1%81%D1%82%D0%B8%D1%82%D1%83%D1%82&amp;t=k&amp;z=16&amp;ie=UTF8&amp;iwloc=&amp;output=embed"
                                        frameborder="0" scrolling="no" style="width: 850px; height: 420px;"></iframe>
                                <style>
                                    .mapouter {
                                        position: relative;
                                        height: 420px;
                                        width: 850px
                                    }

                                    .gmap_canvas {
                                        overflow: hidden;
                                        height: 420px;
                                        width: 850px
                                    }

                                    .gmap_canvas iframe {
                                        position: relative;
                                        z-index: 2
                                    }

                                    .gmap_canvas a {
                                        top: 0;
                                        z-index: 0
                                    }</style>
                                <a href="https://www.eireportingonline.com">ei reporting online</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end contact section -->

{% endblock %}